name: Test

on: [push] # Ejecutar el flujo de trabajo cuando haya un push al repositorio

jobs:
  test:
    runs-on: ubuntu-latest # El sistema operativo en el que se ejecutará el flujo de trabajo

    steps:
    - uses: actions/checkout@v2 # Obtiene el código del repositorio

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Selecciona la versión de Node.js que desees utilizar

    - name: Install dependencies
      run: npm install # Instala las dependencias del proyecto (asegúrate de que el script de prueba esté listado en el package.json)

    - name: Run tests
      run: npm test # Ejecuta el script de prueba (script.test.js)
